name: Android CI

on:
  push:
    branches: [ "develop"  ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu'

    - name: generate local property
      run: |
        echo ATT_BASE_URL=\"$ATT_BASE_URL\" >> local.properties
        echo TMP_ACCESS_TOKEN=\"$TMP_ACCESS_TOKEN\" >> local.properties
        
      env:
        ATT_BASE_URL: ${{ secrets.ATT_BASE_URL }}
        TMP_ACCESS_TOKEN: ${{ secrets.TMP_ACCESS_TOKEN }}
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Unit Test
      run: ./gradlew test

    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: reports
        path: app/build/reports/tests

    - name: Download Test Reports Folder
      uses: actions/download-artifact@v3
      with:
        name: reports
    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0

  merge-branch:
    permissions:
      checks: write
      contents: write
      pull-requests: write
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge staging -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: 'develop'
          github_token: ${{ secrets.GITHUB_TOKEN }}