name: Android CD

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: all-the-time
          file: app/release/app-release.aab
          releaseNotes: |
            ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.html_url }}
            ${{ github.event.pull_request.body }}

  merge-branch:
    permissions:
      checks: write
      contents: write
      pull-requests: write
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge develop -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}